---
title: Takenotes Design Studio
timezone: UTC
collections:
  archives:
    title: Archives
    output: true
    permalink: "/:title/"
  boh:
    title: Boh
    output: true
    permalink: "/backofhouse/:title/"
  pages:
    title: Pages
    output: true
    permalink: "/:title/"
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  work:
    title: Work
    output: true
    permalink: "/work/:title/"
defaults:
- scope:
    path: ''
    type: work
  values:
    layout: casestudy
- scope:
    path: ''
    type: boh
  values:
    layout: boh
- scope:
    path: ''
    type: archives
  values:
    layout: archive
email: ryan@takenot.es
author: Ryan Underwood
description: Takenotes Design Studio is the design studio (desk in my living room)
  of me, Ryan Underwood. I am a non-award winning (It's all politics and I never submit
  anyways. I'm not bitter.) designer, leader, and somewhat of a front-end developer.
brief_desc: The freelance studio of Ryan Underwood. A design leader guiding businesses
  to success.
baseurl: ''
url: ''
canonical_url: http://takenot.es
github: https://github.com/takenot-es
instagram: https://www.instagram.com/noble_whiskers/
linkedin: https://www.linkedin.com/in/ryanwunderwood/
dribbble: https://dribbble.com/ryanunderwood
featured_image: "/assets/media/featured-images/Takenotes-Featured-Image.jpg"
favicon: "/assets/media/featured-images/favicon.png"
google_tag: UA-112100017-1
sass:
  sass_dir: "/assets/sass/"
category:
- Art Direction
- Design System Lead
- Branding
- Front-End Development
- Graphic Designer
- I'm not Carmy
plugins:
- jekyll-feed
